TrainingArguments:
  num_train_epochs: 3                       
  warmup_steps: 500                            
  per_device_train_batch_size: 2               
  per_device_eval_batch_size: 2                  
  weight_decay: 0.01                             
  logging_steps: 50                           
  eval_strategy: 'steps'               
  eval_steps: 1000             
  save_steps: 1000                     
  gradient_accumulation_steps: 8           
  learning_rate: 5e-5                
  fp16: True                         
  save_total_limit: 3 