artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/PhamAnhTienn/Cut-Your-Text/raw/main/data/dialogsum_dataset_csv.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["data.zip", "train.csv", "test.csv", "validation.csv"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path:
    train: artifacts/data_ingestion/train.csv
    test: artifacts/data_ingestion/test.csv
    validation: artifacts/data_ingestion/validation.csv
  tokenizer_name: facebook/bart-large-cnn

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/dialogsum_dataset
  model_ckpt: facebook/bart-large-cnn

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/dialogsum_dataset
  model_path: artifacts/model_trainer/bart-dialogsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv
